### PR TITLE
Improve global behaviour of the app

### PR DESCRIPTION
**Pull request by LGT2**
- Added a "Settings" activity, to adjust difficulty 
- see README.md  for done / todo

### CODE REVIEW

**Comment by Pikamander2** [comment]
Oh wow, thanks for all the changes @LGT2 . I'll take a look over them soon.

I've been meaning to go back and improve this app at some point. In particular, the buttons and text don't scale very well on some devices. Do you happen to know how to fix that?

There also seems to be a rare bug where a kana can get listed as an answer twice. Did you by chance notice that or any other bugs when you were working on it?

**Comment by LGT2** [comment]
I've only tested it on Galaxy S2 and it went fine with buttons resizes. It's hard to tell how to fix without knowing the root cause of the issue.

So far I haven't noticed any bug at all.  (Great job)

**Comment by LGT2** [comment]
Finally I've found one case of duplicate when both ji and dji  or zu dzu  where spelled the same way as respectively ji and zu.  I've added the 'd' letter to distinguish between theses. 
The distinction was already done for hiragana.

**Comment by Pikamander2** [comment]
@LGT2 - Sorry for the extremely long delay. I took a look at your changes and they look great (I made a few small text changes). I'll push the updated version to the store in a day or two.

I don't quite understand the Repetition Count setting though. It appears to be grayed-out and tapping it doesn't do anything.

image

**Comment by LGT2** [comment]
@Pikamander2 - This option is not plugged yet, I originally intended to set a target count , with a limit, after which a summary of statistics should be displayed.  After reading comments, I think it should also be possible to set a maximum time for each response, materialized by a progress bar.

**Pull request merged**
